### ISSUE TITLE
`getHead` in figma-plugin missing Authorization headers

### ISSUE THREAD

**Issue by nwesthoff** [daangn/icona#18]
First of all, amazing work June! It's not quite working for us currently, but it seems to be exactly what we need :) 

I'm unable to deploy icons using Icona, because the call to `/repos/[org]/[repo]/git/refs/heads/main` fails. 
My guess is it's because [`getHead`](https://github.com/daangn/icona/blob/56291ab98ef36598a218b49ab67e05f185af5c9b/packages/figma-plugin/plugin-src/github.ts#L32C1-L36C4) doesn't include authorization headers. This is fine for public repositories, but it's causing issues with private ones.

**Comment by junghyeonsu** [comment]
@nwesthoff 
First of all, I apologize for the delayed response.
I'll look into it! Thanks for reporting the issue.

**Comment by junghyeonsu** [comment]
@nwesthoff Edit this issue in [here](https://github.com/daangn/icona/commit/675550213a4e2c53ef14906dc895df393b2c466a)
